### PR TITLE
Doc changes:

### PR DESCRIPTION
**Pull request by avasquez614**
Added Javadoc for Deployer.

### CODE REVIEW

**Review by alhambrav — CHANGES_REQUESTED** [review]
Here's a list of suggested changes, I suggest fixing typos at least.

DeploymentPipelineFactoryImpl.java
Copyright year not updated to 2017

rest/TargetController.java
line no 65: The body **must** (instead of most) contain
Should it have copyright info at the top of the file?

utils/ConfigUtils.java
line no 207, 227: A String array property **is** normally specified as
line no 208, 228: a String with values **being** (remove being) separated by commas in the configuration 

AbstractSshAuthConfigurator.java
BasicUsernamePasswordAuthConfigurator.java
/utils/git/AbstractSshAuthConfigurator.java
/utils/git/BasicUsernamePasswordAuthConfigurator.java
/utils/git/GitAuthenticationConfigurator.java
/utils/git/SshRsaKeyPairAuthConfigurator.java
/utils/git/SshUsernamePasswordAuthConfigurator.java
Should the files above have copyright info at the top of the file?

ListHelper.java
line no 26: … which means that **it** will only iterate if it’s an

**Comment by avasquez614** [comment]
Applied fixes requested by @alhambrav

**Review by alhambrav — CHANGES_REQUESTED** [review]
rest/TargetController.java
Please add copyright info at the top of the file

utils/ConfigUtils.java
should line no 208 and 228 read like this:
line no 208, 228: a String with values separated by commas in the configuration.

or the original:
a String with values being separated by commas in the configuration.

**Comment by avasquez614** [comment]
Requested fixes applied.

**Review by alhambrav — APPROVED** [review]

**Pull request merged**
